services:
    eplbot:
        build:
            context: .
            target: runtime
            dockerfile: Dockerfile
        image: eplbot
        restart: unless-stopped
        volumes:
            - ./data:/home/eplbot/persistence
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - variables.env