services:
    eplbot:
        build:
            context: .
            target: production
            dockerfile: Dockerfile
        image: eplbot
        restart: unless-stopped
        volumes:
            - ./data:/home/eplbot/persistence
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - variables.env
        ports:
            -   "10001:10001" # Expose possible profiler port