services:
    eplbot:
        image: eplbot
        volumes:
            - eplbot_persistence:/persistence
        env_file:
            -   variables.env
volumes:
    eplbot_persistence:
        external: true