services:
    eplbot:
        image: hokkaydo/eplbot
        restart: unless-stopped
        volumes:
            - /home/docker/data/eplbot:/home/eplbot/persistence
        environment:
            - DISCORD_BOT_TOKEN=${EPLBOT_TOKEN}
            - GITHUB_APPLICATION_ID=${EPLBOT_GITHUBID}
            - GITHUB_APPLICATION_INSTALLATION_ID=${EPLBOT_INSTALLID}
            - TEST_DISCORD_ID=${EPLBOT_DISCORDID}
        
